Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-08, with the labels that each got.

#181 CC-30448: Integration CC-24108
  composer.json
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Stock/Persistence/Propel/Schema/spy_stock.schema.xml
Labels: ready-for-release

#183 CC-30665 Fixed order item count on order detail page.
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-summary/order-summary.twig
Labels: bug, request-review

#188 CC-21846 Fixed product variant selector on the Cart page.
  composer.lock
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/formatted-number-input/formatted-number-input.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-variant-selector/product-item-variant-selector.twig
Labels: bug

#189 CC-29896 Introduced Docker container for Robot tests.
  .github/workflows/ci.yml
  .gitignore
  .robot/Dockerfile
  .robot/docker-compose.robot.yml
  composer.lock
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.dev.yml
Labels: ready-for-release, improvement

#190 CC- 30403: Added merchant expander bulk plugins execution.
  composer.lock
  src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
Labels: ready-for-release

#191 CC-26235 Added extension validation for file upload.
  composer.json
  composer.lock
  data/import/common/common/mime_type.csv
  src/Pyz/Zed/FileManagerGui/FileManagerGuiConfig.php
  src/Pyz/Zed/PriceProductScheduleGui/PriceProductScheduleGuiConfig.php
  src/Pyz/Zed/ProductListGui/ProductListGuiConfig.php
Labels: bug, ready-for-release

#193 CC-31060 Update feature aliases
  composer.json
  composer.lock
Labels: bug, ready-for-release

#194 CC-31061 Fixed Postgres compatibility for push notification BAPI tests.
  composer.lock
Labels: bug, ready-for-release
