Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-12, with the labels that each got.

#281 CC-32034 Fixed Robot package sync issue.
  .dockersyncignore
Labels: bug

#284 CC-31983 Fixed Agent bar
  package-lock.json
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.twig
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/index.ts
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.scss
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/views/quote-request-agent-overview/quote-request-agent-overview.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/logo/logo.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.scss
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.scss
Labels: bug

#289 CC-31629 Fixed submit button disabling on the checkout address step.
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form/address-item-form.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/CompanyWidget/Theme/default/views/company-business-unit-address/company-business-unit-address.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-checkbox/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-checkbox/toggler-checkbox.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-radio/toggler-radio.ts
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
Labels: bug

#290 CC-32131 Fixed merchant portal and Product configurator build for CI acceptance configuration files.
  config/install/docker.ci.acceptance.robot.yml
  deploy.ci.acceptance.mariadb.robot.yml
Labels: bug

#287 CC-31773 Fixed issue with missing shipment price on Order Details page.
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: bug, ready-for-release

#292 CC-32150 Removed redundant services from robot deploy file.
  deploy.ci.acceptance.mariadb.robot.yml
Labels: ready-for-release, request-review, improvement

#294 CC-21163 Fixed ability to create return for bundle products.
  composer.lock
  src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/merchant-sales-return-create-form/merchant-sales-return-create-form.twig
  src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/separate-returns-by-merchant/separate-returns-by-merchant.ts
Labels: bug

#295 CC-32127 Cookies SameSite Lax integration.
  config/Shared/config_default.php
Labels: bug, ready-for-release

#296 CC-30070 Fixed table actions alignment.
  src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/business-unit-address-table/business-unit-address-table.twig
  src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/permission-table/permission-table.twig
  src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/role-table/role-table.twig
  src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/user-table/user-table.twig
  src/Pyz/Yves/CompanyUserInvitationPage/Theme/default/components/molecules/invitation-table/invitation-table.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.twig
  src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/index.ts
  src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/quote-table.scss
  src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/quote-table.twig
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/quote-request-table/quote-request-table.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/views/quote-request-agent-cancel-link/quote-request-agent-cancel-link.twig
  src/Pyz/Yves/QuoteRequestPage/Theme/default/components/molecules/quote-request-view-table/quote-request-view-table.twig
  src/Pyz/Yves/QuoteRequestWidget/Theme/default/views/quote-request-cancel-link/quote-request-cancel-link.twig
  src/Pyz/Yves/SalesReturnPage/Theme/default/templates/page-layout-sales-return/page-layout-sales-return.twig
  src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-list/return-list.twig
  src/Pyz/Yves/SharedCartWidget/Theme/default/views/multi-cart-permission-actions/multi-cart-permission-actions.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/status/status.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-link/table-action-link.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.twig
  src/Pyz/Yves/ShoppingListPage/Theme/default/components/molecules/shopping-list-overview-table/shopping-list-overview-table.twig
  src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list-dismiss-link/shopping-list-dismiss-link.twig
Labels: bug

#298 CC-30070 Fixed table indents.
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
Labels: bug
