Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-03, with the labels that each got.

#50 CC-26176: Add robot tests
  .github/workflows/ci.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
Labels: enhancement, ready-for-release

#59 CC-25813: Tech Debt for AclMerchantPortal module.
  composer.json
  composer.lock
  src/Pyz/Zed/AclEntity/AclEntityDependencyProvider.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
  src/Pyz/Zed/MerchantUser/MerchantUserDependencyProvider.php
Labels: ready-for-release, improvement

#56 CC-25744 Fixed missing number formatting on Sales page.
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageFactory.php
Labels: bug, request-review

#53 SUPESC-603 Fixed product category order overriding during data import
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
Labels: bug

#54 CC-25887 Updated `jquery` dependency version.
  composer.lock
  package-lock.json
  package.json
Labels: ready-for-release, improvement, dependencies

#64 CC-25964 Fixed table features loading behavior.
  composer.json
  composer.lock
  package-lock.json
Labels: bug

#69 SUPESC-606 Fixed filtering by stores in Availability Notifications.
  composer.json
  composer.lock
  config/Shared/config_default.php
  deploy.aop-b2b-testing.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.yml
  deploy.spryker-mp-b2b.yml
  deploy.spryker-mpb2bs.yml
  deploy.yml
Labels: bug, ready-for-release

#71 CC-26417 Replaced discount product label conditions with IN and NOT IN comparators.
  composer.json
  composer.lock
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: bug, ready-for-release

#68 CC-25997 Lowered chunk size for search sync.
  config/Shared/config_default.php
Labels: bug, ready-for-release

#65 SDK-1815 cleanup
  composer.lock
  src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/ProductDetailPageDependencyProvider.php
Labels: improvement

#62 CC-16906 Adjusted session & token validation.
  composer.json
  composer.lock
  config/Zed/cronjobs/jenkins.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorage.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorageQuery.php
  src/Pyz/Client/Oauth/OauthDependencyProvider.php
  src/Pyz/Client/RabbitMq/RabbitMqConfig.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Customer/Persistence/Propel/Schema/spy_customer.schema.xml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
  src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php
Labels: ready-for-release
