Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-07, with the labels that each got.

#148 CC-29960: Added missing mail sender.
  deploy.spryker-mpb2b.yml
Labels: bug

#149 CC-16735: Update discount demo data at b2b-demo-mp
  data/import/common/common/discount.csv
Labels: bug, ready-for-release

#150 CC-29918 Fixed AddressForm's city field input type.
  composer.json
  composer.lock
  package-lock.json
Labels: bug, ready-for-release

#152 CC-29931 Fixed displaying grand total of merchant order after refund
  composer.json
  composer.lock
Labels: bug, request-review

#153 CC-17241 Fixed creating merchant user while firstname and lastname already given.
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalConfig.php
Labels: bug, ready-for-release

#151 CC-29647 Fixed FE Yves commands.
  .prettierrc.js
  composer_back.json
  frontend/libs/command-line-parser.js
  frontend/libs/formatter.js
  frontend/merchant-portal/update-config-paths.js
  frontend/settings.js
  package-lock.json
  package.json
  tsconfig.mp.json
Labels: bug

#157 CC-24090: Fixed checkout address form on submit action.
  composer.json
  composer.lock
Labels: bug, request-review

#156 CC-30090 Adjust CORS configuration for demo shops GLUE APIs
  deploy.spryker-mpb2b.yml
Labels: ready-for-release

#154 CC-30009 Fixed ability to change default price (RFQ).
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/source-price-form/source-price-form.ts
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/source-price-form/source-price-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/input/input.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/textarea/textarea.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/formatted-number-input/formatted-number-input.scss
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
Labels: bug

#159 CC-30078 Fixed users search for agent
  composer.json
  composer.lock
Labels: bug

#170 CC-29892: Adjust demo data to remove redundant payment method
  data/import/common/AT/payment_method_store.csv
  data/import/common/DE/payment_method_store.csv
  data/import/common/US/payment_method_store.csv
  data/import/common/common/payment_method.csv
Labels: ready-for-release

#173 CC-16486 Fix the self-link for the product review resource.
  composer.lock
  src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
Labels: bug, ready-for-release

#175 FRW-1992 and FRW-2313 Integration
  composer.json
  composer.lock
Labels: bug, request-review

#177 FRW-2432 FRW-2377 Fixed Oauth token saving if it already exists. Fixed disabling CORS headers.
  composer.json
  composer.lock
Labels: bug

#174 CC-25992: Adjusted login mechanism for agent and customer.
  composer.lock
  src/Pyz/Yves/SecurityBlockerPage/SecurityBlockerPageConfig.php
Labels: bug

#171 CC-30037: Fixed cart page product items sum display.
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.twig
  src/Pyz/Yves/CartPage/Theme/default/components/organisms/cart-sidebar/cart-sidebar.twig
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart-preview/page-layout-cart-preview.twig
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
Labels: bug, ready-for-release
