Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-05, with the labels that each got.

#93 CC-26567 Internal Robot UI CI tests
  .github/workflows/ci.yml
  .github/workflows/robot-ui.yml
Labels: ready-for-release

#87 CC-15817 Added additional validation to form fields.
  composer.lock
  data/import/common/common/cms_block.csv
Labels: bug, ready-for-release

#92 CC-16536 Added alternative abstract products to the import file
  data/import/common/common/product_alternative.csv
Labels: bug, ready-for-release

#90 CC-25966 Added additional validation for company role form.
  composer.lock
  data/import/common/common/glossary.csv
Labels: bug, ready-for-release

#97 SUPESC-605: Fix an exception on company user delete
  composer.lock
  src/Pyz/Zed/CompanyUser/CompanyUserDependencyProvider.php
Labels: bug

#104 CC-28284 Enabled runtime events for Backend API.
  src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
Labels: bug, ready-for-release

#101 CC-17164 Fixed product offer availability when product offer is not assigned to a store.
  composer.json
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug

#103 CC-28304 Updated Service Point Patch validation.
  config/install/ci.yml
  config/install/development.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.yml
  config/install/docker.ci.functional.yml
  config/install/docker.yml
  config/install/testing.yml
Labels: bug, ready-for-release

#57 SUPESC-685 Fixed session storage overloading by Quote Collection data
  src/Pyz/Client/MultiCart/MultiCartConfig.php
Labels: bug, request-review

#109 CC-26820 Fixed breadcrumbs for a product integration.
  composer.json
  composer.lock
  src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php
Labels: bug, ready-for-release
