Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-11, with the labels that each got.

#243 CC-31728 Update npm dependencies
  composer.lock
  package-lock.json
  package.json
Labels: bug, dependencies

#246 SUPESC-754 Fixed Shopping Lists unsharing.
  composer.json
  composer.lock
Labels: bug

#248 CC-31801 Fixed exception when setting merchant relation price.
  src/Pyz/Zed/ProductManagement/Presentation/_partials/product_volume_price_action_button.twig
Labels: ready-for-release

#250 FRW-6810 Fixed config file for DDE API
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#251 CC-31780 Fixed caching of categories in discounts.
  composer.json
  composer.lock
Labels: bug

#252 CC-31787 Fixed preselected address state for multiple addresses at checkout
  composer.json
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
Labels: bug, ready-for-release

#253 CC-31798 Fix yves product color selectors
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductGroupWidget/Theme/default/components/molecules/color-selector/color-selector.twig
Labels: bug, ready-for-release

#255 CC-25879 Decreased memory usage in product data import.
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepository.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepositoryInterface.php
  src/Pyz/Zed/DataImport/Business/Model/ProductConcrete/ProductConcreteAttributesUniqueCheckStep.php
  src/Pyz/Zed/DataImport/DataImportConfig.php
Labels: bug

#257 CC-31782 Fixed address state for multiple addresses
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
Labels: bug, ready-for-release

#256 CC-29270 Fixed merchant product offer storage memory leak.
  composer.json
  composer.lock
Labels: bug

#260 CC-26145: Enhance Comment Validation for User-Specific Orders/Quotes
  composer.json
  composer.lock
  src/Pyz/Zed/Comment/CommentDependencyProvider.php
Labels: bug, ready-for-release

#267 Bulk bugfixes integration
  composer.json
  composer.lock
  tests/PyzTest/Glue/ProductConfigurations/RestApi/Fixtures/ProductConfigurationsRestApiFixtures.php
Labels: bug

#273 Release 202311.0 to internal merge
  composer.json
  composer.lock
  config/Shared/config_default-docker.dev.php
  src/Orm/Zed/SalesShipmentType/Persistence/SpySalesShipmentType.php
  src/Orm/Zed/SalesShipmentType/Persistence/SpySalesShipmentTypeQuery.php
  src/Pyz/Client/Catalog/CatalogDependencyProvider.php
  src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Client/ProductNew/ProductNewDependencyProvider.php
  src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php
  src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
  src/Pyz/Glue/GlueStorefrontApiApplication/GlueStorefrontApiApplicationDependencyProvider.php
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductGroupWidget/Theme/default/components/molecules/color-selector/color-selector.twig
  src/Pyz/Zed/Authorization/AuthorizationConfig.php
  src/Pyz/Zed/Comment/CommentDependencyProvider.php
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepository.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepositoryInterface.php
  src/Pyz/Zed/DataImport/Business/Model/ProductConcrete/ProductConcreteAttributesUniqueCheckStep.php
  src/Pyz/Zed/DataImport/DataImportConfig.php
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
  src/Pyz/Zed/ProductManagement/Presentation/_partials/product_volume_price_action_button.twig
  tests/PyzTest/Glue/ProductConfigurations/RestApi/Fixtures/ProductConfigurationsRestApiFixtures.php
  tests/PyzTest/Zed/MessageBroker/_bootstrap.php
  tests/PyzTest/Zed/MessageBroker/codeception.yml
Labels: request-review

#268 CC-31839 Fixed multiple addresses state on Checkout.
  composer.json
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CompanyWidget/Theme/default/views/company-business-unit-address/company-business-unit-address.twig
Labels: bug, ready-for-release

#278 CC-26451: Password reset workflow improvements.
  composer.json
  composer.lock
Labels: bug

#274 CC-31756 `main-overlay` component integration.
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/overlay-block/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/overlay-block/overlay-block.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/overlay-block/overlay-block.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/overlay-block/overlay-block.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel/navigation-multilevel.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel/navigation-multilevel.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/overlay-enabler/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/overlay-enabler/overlay-enabler.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/overlay-enabler/overlay-enabler.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search-extended.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/account-navigation/account-navigation.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.twig
  src/Pyz/Yves/ShopUi/Theme/default/styles/settings/_z-index.scss
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
Labels: improvement
