Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2023-06, with the labels that each got.

#72 CC-26286 Bugfix for packaging units hint
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/measurement-unit/index.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/measurement-unit/measurement-unit.scss
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/index.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.scss
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.twig
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/product-packaging-new-price/index.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/product-packaging-new-price/product-packaging-new-price.scss
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/views/pdp-product-packaging-unit/pdp-product-packaging-unit.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.twig
  tsconfig.yves.json
Labels: bug, ready-for-release

#111 CC-25629 Updated Node.js to v18.
  .github/workflows/ci.yml
  .nvmrc
  composer.json
  deploy.aop-b2b-testing.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.spryker-mp-b2b.yml
  deploy.spryker-mpb2bs.yml
  deploy.yml
  frontend/configs/development.js
  package-lock.json
  package.json
  tsconfig.yves.json
Labels: improvement

#74 CC-16903 Adjusted login mechanism for Backoffice and Merchant Portal.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Client/SecurityBlocker/SecurityBlockerDependencyProvider.php
  src/Pyz/Zed/ErrorHandler/ErrorHandlerConfig.php
  src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: bug, ready-for-release

#113 CC-28473 Fixed date-picker validity dates.
  composer.lock
  package-lock.json
Labels: bug

#114 CC-23397: Added resource relationship support for Backend API.
  src/Pyz/Glue/DocumentationGeneratorApi/DocumentationGeneratorApiDependencyProvider.php
Labels: bug, request-review

#85 CC-25835: Fixed backoffice return creation.
  src/Pyz/Zed/SalesReturnGui/SalesReturnGuiDependencyProvider.php
Labels: bug, ready-for-release

#129 CC-29685: Adjusted installation configuration to fix an issue on AT store.
  config/install/docker.yml
Labels: bug, ready-for-release

#130 CC-29660 Fixed displaying approval statuses on shipping cart
  src/Pyz/Client/MultiCart/MultiCartConfig.php
Labels: bug, ready-for-release

#137 CC-29908 Raised date time configurator version
  composer.json
  composer.lock
Labels: ready-for-release

#140 CC-29900 Fixed refund for marketplace integration.
  src/Pyz/Zed/Refund/RefundDependencyProvider.php
Labels: bug, ready-for-release

#135 CC-21301: Fixed invalid checkout payment
  composer.json
  composer.lock
  src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php
Labels: bug, ready-for-release
