Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-06, with the labels that each got.

#395 FRW-8567 Integration
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: improvement, robot-regression-ui-e2e

#398 CC-33735 Fixed production import manifest file
  data/import/production/full_US.yml
Labels: ready-for-release, robot-regression-ui-e2e

#399 CC-33728: Added Missing Demo Data for Merchant Special Opening Hours.
  .github/workflows/ci.yml
  composer.lock
  data/import/common/common/marketplace/merchant_open_hours_date_schedule.csv
Labels: bug, ready-for-release

#400 CC-33310: Introduced the workflow to auto-merge the latest release to the "master-deploy" branch.
  .github/workflows/up-merge-latest-release-to-master-deploy.yml
Labels: request-review
