Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-08, with the labels that each got.

#410 CC-34112: Shared cart fatal error integration
  composer.lock
Labels: robot-regression-ui-e2e

#413 ACP-2626: Stripe marketplace payment flow -fix
  config/Shared/config_default.php
Labels: robot-regression-ui-e2e

#415 ACP-3675: Update redirect.php
  public/MerchantPortal/redirect.php
Labels: skip-robot-regression-ui-e2e

#414 ACP-3589: Sales Payment details integration
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: skip-robot-regression-ui-e2e

#408 ACP-3544: Added MP
  deploy.aop-demoshop-b2b.yml
Labels: skip-robot-regression-ui-e2e

#421 MP payment transfers with commission fixes for OMS (patches)
  composer.lock
Labels: skip-robot-regression-ui-e2e

#423 FRW-8868 Hackhaton CI.
  .github/workflows/ci.yml
Labels: skip-robot-regression-ui-e2e

#424 FRW-8932 Marketplace homepage fix integration.
  composer.lock
  src/Pyz/Zed/MerchantPortalApplication/Communication/MerchantPortalApplicationCommunicationFactory.php
  src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationConfig.php
Labels: skip-robot-regression-ui-e2e

#425 FRW-8938 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
Labels: skip-robot-regression-ui-e2e, hackathon

#426 CC-34261 Split navigation for MP and BO.
  composer.lock
  config/Zed/navigation-main-merchant-portal.xml
  config/Zed/navigation-secondary-merchant-portal.xml
  config/Zed/navigation.xml
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
  src/Pyz/Zed/ZedNavigation/ZedNavigationConfig.php
Labels: skip-robot-regression-ui-e2e
