Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-11, with the labels that each got.

#485 CC-34732 Update Summernote dependency
  composer.lock
  package-lock.json
Labels: ready-for-release, robot-regression-ui-e2e

#486 FRW-8773 PHP Unit 11 Support Integration.
  composer.json
  composer.lock
  tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
  tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
  tests/PyzTest/Yves/Availability/Presentation/AvailabilityAddToCartCest.php
  tests/PyzTest/Yves/Availability/_support/AvailabilityPresentationTester.php
  tests/PyzTest/Yves/Checkout/Process/Steps/AddressStepTest.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SuccessStepTest.php
  tests/PyzTest/Yves/CompanyUser/Presentation/CompanyRegistrationCest.php
  tests/PyzTest/Yves/CompanyUser/_support/CompanyUserPresentationTester.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerAddressCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerAddressesCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerLoginCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerLogoutCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerNewsletterCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerOverviewCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerProfileCest.php
  tests/PyzTest/Yves/Customer/_support/CustomerPresentationTester.php
  tests/PyzTest/Yves/Newsletter/Presentation/NewsletterSubscriptionCest.php
  tests/PyzTest/Yves/Newsletter/_support/NewsletterPresentationTester.php
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiPageListCest.php
  tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
  tests/PyzTest/Zed/Console/Console/ConsoleCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentAuthorizedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCanceledMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCaptureFailedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCapturedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentRefundFailedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentRefundedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/_support/PaymentPresentationTester.php
  tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
  tests/PyzTest/Zed/NavigationGui/Presentation/NavigationTreeCest.php
  tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
  tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
  tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php
  tests/PyzTest/Zed/Tax/Presentation/TaxRateCreateCest.php
  tests/PyzTest/Zed/Tax/_support/TaxPresentationTester.php
Labels: enhancement, robot-regression-ui-e2e

#488 FRW-7399 Fixed product set and product review search stores data.
  .github/workflows/ci.yml
  composer.lock
  src/Pyz/Client/ProductSetPageSearch/ProductSetPageSearchDependencyProvider.php
Labels: bug, robot-regression-ui-e2e

#489 FRW-8965 Optimized CI pipelines.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
Labels: improvement, robot-regression-ui-e2e

#493 CC-34804 Fixed exception on Manage Company Roles page.
  data/import/common/common/company_role_permission.csv
  data/import/common/common/glossary.csv
Labels: robot-regression-ui-e2e
