Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-09, with the labels that each got.

#428 CC-34258: Multi-select attribute values (Fixathon)
  composer.lock
  data/import/common/common/product_abstract.csv
  data/import/common/common/product_attribute_key.csv
  data/import/common/common/product_management_attribute.csv
  src/Pyz/Glue/ProductsRestApi/ProductsRestApiDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-detail/product-detail.twig
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
  src/Pyz/Zed/ProductAttribute/ProductAttributeConfig.php
  src/Pyz/Zed/ProductAttribute/ProductAttributeDependencyProvider.php
Labels: request-review, robot-regression-ui-e2e

#429 CC-13685: Updated product quantity and total in Mini Cart Widget from catalog AJAX add-to-cart action.
  composer.lock
Labels: request-review, robot-regression-ui-e2e

#430 FRW-8766 Order matrix performance improvement integration.
  composer.lock
  config/Zed/cronjobs/jenkins.php
  config/Zed/navigation.xml
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#431 ACP-3558 Merchant payment expense support.
  composer.lock
  config/Shared/config_default-docker.dev.php
  src/Pyz/Zed/SalesPaymentMerchant/SalesPaymentMerchantConfig.php
Labels: robot-regression-ui-e2e

#432 ACP-3824: updated composer, Added acl plugin
  composer.lock
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
Labels: robot-regression-ui-e2e

#434 CC-33982: P&S optimisation.
  composer.lock
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/CustomerAccessStorage/Persistence/Propel/Schema/spy_unauthenticated_customer_access_storage.schema.xml
  src/Pyz/Zed/Event/EventConfig.php
  src/Pyz/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
  src/Pyz/Zed/TaxProductStorage/Persistence/Propel/Schema/spy_tax_product_storage.schema.xml
Labels: request-review, robot-regression-ui-e2e

#435 FRW-7903 Integration
  composer.lock
  src/Pyz/Zed/Product/ProductConfig.php
Labels: bug, skip-robot-regression-ui-e2e

#437 CC-26445 Integration
  src/Pyz/Yves/CustomerPage/CustomerPageConfig.php
Labels: bug, skip-robot-regression-ui-e2e

#439 FRW-8801 Added PHP 8.3 support.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  .scrutinizer.yml
  README.md
  composer.json
  composer.lock
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.robot.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.scos2-b2bmp.yml
  deploy.spryker-mp-b2b.yml
  deploy.spryker-mpb2bs.yml
  deploy.spryker-scosb2bmp.yml
  deploy.yml
  phpcs.xml
  src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: improvement, robot-regression-ui-e2e
