Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-10, with the labels that each got.

#444 ACP-3661: Integrated the ACL entity synchronization command.
  composer.json
  composer.lock
  config/install/EU/production.yml
  config/install/US/production.yml
  config/install/production.dynamic-store.yml
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Labels: robot-regression-ui-e2e

#446 FWR-9121 Fixed broken robot test
  composer.json
  composer.lock
  src/Pyz/Zed/DynamicEntity/DynamicEntityDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#436 FRW-8878 Integrated router performance issue fix.
  composer.lock
  src/Pyz/Zed/Router/RouterConfig.php
Labels: robot-regression-ui-e2e

#442 CC-34423 Product Concrete table in MP integration
  composer.json
  composer.lock
  config/Zed/navigation-main-merchant-portal.xml
  data/import/common/AT/discount_store.csv
  data/import/common/DE/discount_store.csv
  data/import/common/US/discount_store.csv
  data/import/common/common/discount.csv
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: ready-for-release, improvement, robot-regression-ui-e2e

#449 FRW-9030 SUPESC Integrations
  composer.lock
Labels: robot-regression-ui-e2e

#450 FRW-7443 Store Context integration.
  composer.lock
  data/import/common/AT/store_context.csv
  data/import/common/DE/store_context.csv
  data/import/common/EU/store_context.csv
  data/import/common/US/store_context.csv
  data/import/common/commerce_setup_import_config_EU.yml
  data/import/common/commerce_setup_import_config_US.yml
  data/import/common/minimal.yml
  data/import/local/full_EU.yml
  data/import/local/full_US.yml
  data/import/production/full_EU.yml
  data/import/production/full_US.yml
  src/Pyz/Client/Store/StoreDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Store/StoreDependencyProvider.php
  src/Pyz/Zed/StoreContext/Persistence/Propel/Schema/spy_store_context.schema.xml
  src/Pyz/Zed/StoreGui/StoreGuiDependencyProvider.php
Labels: robot-regression-ui-e2e

#452 CC-34500 Adjusted merchant commission calculation to not rely on price mode per store configuration.
  composer.lock
  src/Pyz/Zed/MerchantCommission/MerchantCommissionConfig.php
Labels: request-review, improvement, robot-regression-ui-e2e

#454 FRW-9030 Integrations part 4
  composer.json
  composer.lock
Labels: robot-regression-ui-e2e

#451 FRW-8761 Adjusted configuration
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: skip-robot-regression-ui-e2e

#447 FRW-9030 Integrations part 1
  composer.lock
Labels: robot-regression-ui-e2e

#457 FRW-9164 Added extension point to the VariantTable.
  composer.lock
Labels: skip-robot-regression-ui-e2e

#460 FRW-9176 Integration.
  composer.lock
  src/Pyz/Zed/MerchantGui/MerchantGuiDependencyProvider.php
Labels: robot-regression-ui-e2e

#456 FRW-9030 Integrations part 5
  composer.lock
Labels: robot-regression-ui-e2e

#458 FRW-1633 Integrations
  .git.docker
  composer.lock
Labels: robot-regression-ui-e2e

#464 CC-34672 Collapsible category tree integraton
  composer.json
  composer.lock
  package-lock.json
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
  tsconfig.mp.json
Labels: ready-for-release, robot-regression-ui-e2e

#465 FRW-9170: integration
  composer.lock
Labels: robot-regression-ui-e2e

#467 FRW-6475 Fixed product label localized attributes for DS.
  composer.lock
  config/install/docker.ci.functional.yml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug, robot-regression-ui-e2e

#470 CC-34707 Accessibility issue wrong color on State Machine button in Backoffice
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e

#469 CC-34696: CC-34695: integrations.
  composer.json
  composer.lock
Labels: robot-regression-ui-e2e

#468 Release 202410.0
  composer.json
  composer.lock
  config/install/docker.ci.functional.yml
  data/import/common/common/glossary.csv
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant-b2c.yml
  deploy.aop-demoshop-b2b.yml
  deploy.scos2-b2bmp.yml
  deploy.spryker-mp-b2b.yml
  deploy.spryker-mpb2bs.yml
  deploy.spryker-scosb2bmp.yml
  src/Pyz/Client/Permission/PermissionDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SuccessStepTest.php
Labels: robot-regression-ui-e2e

#478 FRW-9241 Adjusted installation configs
  config/install/ci.yml
  config/install/development.yml
  config/install/docker.ci.acceptance.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.robot.yml
  config/install/docker.ci.acceptance.dynamic-store-off.yml
  config/install/docker.ci.acceptance.robot.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.dynamic-store-off.yml
  config/install/docker.ci.api.yml
  config/install/docker.yml
  config/install/testing.yml
Labels: bug, robot-regression-ui-e2e
