Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-05, with the labels that each got.

#366 FRW-7507 Upgraded Jenkins version.
  .git.docker
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.scos2-b2bmp.yml
  deploy.spryker-mpb2bs.yml
  deploy.spryker-scosb2bmp.yml
  deploy.yml
Labels: improvement

#377 FRW-7403 Integrated upgraded PHPStan and bugs.
  composer.json
  composer.lock
  src/Pyz/Zed/Transfer/TransferConfig.php
Labels: improvement

#379 CC-33312: Added E2E Cypress UI tests into CI process for Dynamic multistore.
  .github/workflows/ci.yml
  composer.lock
  config/install/docker.ci.acceptance.dynamic-store.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
Labels: ready-for-release

#382 Added new UI ci yml with jobs
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  composer.lock
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
Labels: enhancement, ready-for-release

#389 FRW-7201 Integration
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: improvement, robot-regression-ui-e2e
