Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2024-12, with the labels that each got.

#496 FRW-9423 Fixed twig error for product view in Merchant Portal.
  .robot/Dockerfile
  composer.lock
  package-lock.json
Labels: robot-regression-ui-e2e

#490 ACP-4516: Integrated Algolia events
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig
  src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/variant-configurator/variant-configurator.twig
  src/Pyz/Yves/ProductSearchWidget/Theme/default/components/molecules/product-search-autocomplete-form/product-search-autocomplete-form.twig
  src/Pyz/Yves/ProductSetDetailPage/Theme/default/views/set-detail/set-detail.twig
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
  src/Pyz/Yves/Twig/TwigDependencyProvider.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/SearchHttp/Communication/SearchEndpointMessageTest.php
  tests/PyzTest/Zed/MessageBroker/_support/SearchHttpCommunicationTester.php
  tests/PyzTest/Zed/MessageBroker/codeception.yml
Labels: robot-regression-ui-e2e

#492 CC-34874 Fixed Merchant Commission export
  src/Pyz/Service/DataExport/DataExportDependencyProvider.php
Labels: bug, ready-for-release, robot-regression-ui-e2e

#502 ACP-4615: Update of the modules.
  composer.lock
Labels: bug, ready-for-release

#491 Integration: CC-20625
  composer.lock
  package-lock.json
Labels: bug, skip-robot-regression-ui-e2e

#473 FRW-8354 Create DMS acceptance tests.
  .github/workflows/ci.yml
  composer.lock
  tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
Labels: skip-robot-regression-ui-e2e

#494 FRW-7936 Integration.
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Yves/Router/RouterConfig.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/StorageRouter/StorageRouterConfig.php
  src/Pyz/Yves/StorageRouter/StorageRouterDependencyProvider.php
  src/SprykerConfig/CodeBucketConfig.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerOverviewCest.php
  tests/PyzTest/Yves/Customer/_support/CustomerPresentationTester.php
  tests/PyzTest/Yves/Customer/_support/PageObject/CustomerOverviewPage.php
Labels: improvement, robot-regression-ui-e2e

#509 SUPESC-859 Updated composer
  composer.lock
Labels: robot-regression-ui-e2e

#513 CC-14130: Fix memory leak on Backoffice ODP page with 100+ items.
  composer.lock
Labels: bug, request-review, skip-robot-regression-ui-e2e

#512 CC-34335: update webpack
  package-lock.json
  package.json
Labels: skip-robot-regression-ui-e2e

#516 CC-34976 Integrate discount improvements
  composer.json
  composer.lock
  data/import/common/AT/discount_store.csv
  data/import/common/DE/discount_store.csv
  data/import/common/common/discount.csv
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: enhancement, request-review, hackathon

#511 FRW-9299 Integrated Profiler enabling.
  composer.lock
  config/Shared/config_default-docker.dev.php
  config/Shared/config_default.php
  src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationDependencyProvider.php
  src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiConfig.php
Labels: skip-robot-regression-ui-e2e, hackathon

#508 FRW-9287 Added new twig var dumper plugin.
  composer.lock
  src/Pyz/Yves/Twig/TwigDependencyProvider.php
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#515 SUPESC-897 Improved performance of BundledProductTable.
  composer.lock
Labels: bug, skip-robot-regression-ui-e2e

#518 CC-35021: Updated cypress hash.
  composer.lock
  package-lock.json
Labels: bug, skip-robot-regression-ui-e2e

#519 CC-35021: Updated cypress hash.
  composer.lock
Labels: skip-robot-regression-ui-e2e

#517 FRW-9071 Integration.
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Glue/CustomersRestApi/Validation/customers.validation.yaml
  src/Pyz/Yves/CustomerPage/CustomerPageConfig.php
  src/Pyz/Zed/Customer/CustomerConfig.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerPasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRegistrationCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRestorePasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerUpdateCest.php
  tests/PyzTest/Yves/CompanyUser/_support/PageObject/CompanyRegistrationPage.php
Labels: improvement, robot-regression-ui-e2e

#498 FRW-9013 Integration.
  composer.lock
  src/Pyz/Zed/Customer/CustomerConfig.php
Labels: robot-regression-ui-e2e

#522 FRW-9641 Integration
  composer.lock
  src/Pyz/Glue/CustomersRestApi/Validation/customers.validation.yaml
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerPasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRegistrationCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRestorePasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerUpdateCest.php
Labels: enhancement, robot-regression-ui-e2e

#527 FRW-9475 Fixed issue with new entity saving for DataExchangeAPI child relations.
  composer.lock
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: robot-regression-ui-e2e

#523 FRW-922 Upgraded predis library to version 2.3.0.
  composer.lock
Labels: improvement, robot-regression-ui-e2e

#525 ACP-4631: MessageBus observability improvement
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e
