Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-02, with the labels that each got.

#539 CC-34804: Exception on Manage Company Roles tests
  composer.lock
  package-lock.json
Labels: run-ui-ci, run-static-ci, run-npm-ci

#542 CC-35203 Fixes tests and adds datepicker plugin
  composer.lock
  package-lock.json
  package.json
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
Labels: run-ui-ci, run-static-ci, run-latest-ci

#541 FRW-9083 Integration
  composer.json
  composer.lock
  data/import/common/AT/cms_block_store.csv
  data/import/common/DE/cms_block_store.csv
  data/import/common/US/cms_block_store.csv
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  src/Orm/Zed/CustomerDataChangeRequest/Persistence/SpyCustomerDataChangeRequest.php
  src/Orm/Zed/CustomerDataChangeRequest/Persistence/SpyCustomerDataChangeRequestQuery.php
  src/Pyz/Yves/LanguageSwitcherWidget/Theme/default/components/molecules/language-switcher/language-switcher.twig
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Customer/CustomerDependencyProvider.php
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
  src/Pyz/Zed/Mail/MailDependencyProvider.php
Labels: run-ui-ci, run-static-ci, run-functional-ci, run-compatibility-ci, run-api-ci, run-latest-ci, run-npm-ci

#545 SUPESC-941 + SUPESC-942 Merchant Portal performance improvements.
  composer.lock
  src/Pyz/Zed/ZedNavigation/ZedNavigationConfig.php
Labels: run-static-ci, run-functional-ci, run-compatibility-ci
