Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-05, with the labels that each got.

#590 Update Jenkins version to 2.493.2
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant-b2c.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.scos2-b2bmp.yml
  deploy.spryker-mp-b2b.yml
  deploy.spryker-mpb2bs.yml
  deploy.spryker-scosb2bmp.yml
  deploy.yml
Labels: run-latest-ci

#596 CC-35691: fixes accessibility
  data/import/common/common/glossary.csv
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/MerchantOpeningHoursWidget/Theme/default/components/molecules/date-information-item/date-information-item.scss
  src/Pyz/Yves/MerchantPage/Theme/default/components/molecules/information-item/information-item.scss
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-configurator/product-configurator.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/select/select.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/privacy-navigation/privacy-navigation.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/styles/settings/_color.scss
  src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list/shopping-list.twig
Labels: bug, run-latest-ci

#593 CC-35650 April 2025 integrations.
  composer.lock
  tests/PyzTest/Yves/Checkout/Process/Steps/ShipmentStepTest.php
Labels: run-static-ci, run-latest-ci, run-npm-ci

#612 FRW-10406 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Sitemap/SitemapDependencyProvider.php
Labels: improvement, run-static-ci, run-functional-ci

#613 CC-35509: remove weekly ci
  .github/actions/job-slack-notifications/action.yml
  .github/actions/scheduled-job-slack-notifications/action.yml
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-compatibility-ci, run-latest-ci

#619 CC-35509 Remove label check at static validation ci job.
  .github/workflows/ci.yml
Labels: improvement, run-compatibility-ci, run-latest-ci

#621 CC-35775 Remove obsolete CI jobs.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-compatibility-ci, run-latest-ci

#622 SUPESC-899 svg sprite asset generation integration
  .gitignore
  composer.lock
  frontend/configs/development.js
  frontend/libs/icon-sprite-extractor.js
  frontend/settings.js
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.twig
Labels: run-latest-ci

#608 CC-35515 Fixed CompanyBusinessUnitAddressCheckoutDataRestApiCest.
  tests/PyzTest/Glue/Checkout/RestApi/CompanyBusinessUnitAddressCheckoutDataRestApiCest.php
Labels: bug, run-static-ci, run-latest-ci
