Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-04, with the labels that each got.

#571 SSP master latest releases
  composer.lock
  config/Shared/config_default-docker.dev.php
  config/Shared/config_default.php
  data/import/common/AT/cms_block_store.csv
  data/import/common/DE/cms_block_store.csv
  data/import/common/US/cms_block_store.csv
  data/import/common/common/cms_block.csv
  data/import/common/common/content_banner.csv
  data/import/common/common/glossary.csv
  frontend/assets/global/default/images/400x200.png
  src/Orm/Zed/SspAssetManagement/Persistence/SpySspAsset.php
  src/Orm/Zed/SspAssetManagement/Persistence/SpySspAssetQuery.php
  src/Orm/Zed/SspAssetManagement/Persistence/SpySspAssetToCompanyBusinessUnit.php
  src/Orm/Zed/SspAssetManagement/Persistence/SpySspAssetToCompanyBusinessUnitQuery.php
  src/Orm/Zed/SspFileManagement/Persistence/SpyCompanyBusinessUnitFile.php
  src/Orm/Zed/SspFileManagement/Persistence/SpyCompanyBusinessUnitFileQuery.php
  src/Orm/Zed/SspFileManagement/Persistence/SpyCompanyFile.php
  src/Orm/Zed/SspFileManagement/Persistence/SpyCompanyFileQuery.php
  src/Orm/Zed/SspFileManagement/Persistence/SpyCompanyUserFile.php
  src/Orm/Zed/SspFileManagement/Persistence/SpyCompanyUserFileQuery.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquiry.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquiryFile.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquiryFileQuery.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquiryQuery.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquirySalesOrder.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquirySalesOrderItem.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquirySalesOrderItemQuery.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquirySalesOrderQuery.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquirySspAsset.php
  src/Orm/Zed/SspInquiryManagement/Persistence/SpySspInquirySspAssetQuery.php
  src/Pyz/Client/CmsBlockStorage/CmsBlockStorageDependencyProvider.php
  src/Pyz/Shared/SspInquiryManagement/SspInquiryManagementConfig.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/SspDashboardManagement/Theme/default/components/molecules/dashboard-table/dashboard-table.twig
  src/Pyz/Yves/SspDashboardManagement/Theme/default/views/dashboard-menu-item/dashboard-menu-item.twig
  src/Pyz/Yves/SspDashboardManagement/Theme/default/views/dashboard/dashboard.twig
  src/Pyz/Zed/FileManager/FileManagerDependencyProvider.php
  src/Pyz/Zed/Kernel/KernelConfig.php
  src/Pyz/Zed/Permission/PermissionDependencyProvider.php
  src/Pyz/Zed/SspAssetManagement/SspAssetManagementConfig.php
  src/Pyz/Zed/SspAssetManagement/SspAssetManagementDependencyProvider.php
  src/Pyz/Zed/SspDashboardManagement/SspDashboardManagementDependencyProvider.php
  src/Pyz/Zed/SspInquiryManagement/SspInquiryManagementConfig.php
  src/Pyz/Zed/SspInquiryManagement/SspInquiryManagementDependencyProvider.php
  src/Pyz/Zed/Translator/TranslatorConfig.php
Labels: run-compatibility-ci, run-latest-ci

#569 CC-22722: Order Sequence Generation integration
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Yves/MultiCartWidget/Theme/default/components/molecules/mini-cart-detail/mini-cart-detail.twig
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: improvement, run-ui-ci, run-static-ci, run-latest-ci

#578 Integration: FRW-9661, FRW-9444, FRW-9438
  composer.lock
Labels: run-static-ci, run-latest-ci

#580 CC-26244: [Performance] Quote is validated twice in Yves CartController
  composer.lock
  src/Pyz/Yves/CartPage/CartPageConfig.php
Labels: bug, run-ui-ci, run-static-ci

#585 CC-35415: B2B yves range date picker has poor accessibility
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-filters/order-filters.twig
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/views/quote-request-edit/quote-request-edit.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
Labels: run-latest-ci

#586 CC-34245 bootstrap upgrade integration
  composer.lock
  package-lock.json
  package.json
Labels: run-latest-ci

#587 CC-35490 Fixed flaky CMS page test.
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
  tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
Labels: bug, run-static-ci, run-compatibility-ci

#588 CC-35103 Add P&S into destructive deployment.
  config/install/destructive.yml
Labels: run-static-ci, run-npm-ci
