Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-07, with the labels that each got.

#649 OPS-4941 Updated RabbitMQ version
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.spryker-mp-b2b.yml
  deploy.spryker-mpb2bs.yml
  deploy.yml
Labels: improvement, run-ui-ci, run-static-ci, run-functional-ci, run-api-ci, run-latest-ci

#650 FRW-901 Integrations.
  composer.lock
Labels: bug, run-ui-ci, run-latest-ci

#655 Itegration
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
Labels: run-ui-ci, run-functional-ci

#668 CC-35846: Added timezone to Order Table filters.
  composer.lock
  src/Pyz/Zed/Store/StoreDependencyProvider.php
Labels: request-review, run-static-ci

#667 AE-212 Integration Measurement Unit Gui
  composer.json
  composer.lock
  config/Zed/navigation.xml
  tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
Labels: enhancement, improvement, run-latest-ci

#671 FRW-10741 Agent MFA integration.
  composer.lock
  src/Pyz/Yves/AgentPage/Theme/default/components/molecules/agent-navigation/agent-navigation.twig
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/set-up-page.twig
Labels: improvement, run-ui-ci

#680 FRW-10759 Integrations and fixes.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/user-set-up-page.twig
  src/Pyz/Zed/Transfer/TransferConfig.php
Labels: bug, dependencies, run-ui-ci, run-static-ci, run-functional-ci, run-latest-ci

#676 FRW-10736 Integration.
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-card/category-card.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-list-item/category-list-item.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
  src/Pyz/Yves/MerchantProductOfferWidget/Theme/default/components/molecules/merchant-product-offer-item/merchant-product-offer-item.twig
  src/Pyz/Yves/MerchantProductWidget/Theme/default/components/molecules/merchant-product-item/merchant-product-item.twig
  src/Pyz/Yves/MerchantRelationRequestPage/Theme/default/views/merchant-relation-request-details/merchant-relation-request-details.twig
  src/Pyz/Yves/MerchantRelationshipPage/Theme/default/views/detail/detail.twig
  src/Pyz/Yves/MerchantWidget/Theme/default/components/molecules/sold-by-merchant/sold-by-merchant.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductSetListPage/Theme/default/components/molecules/product-set-card/product-set-card.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.twig
  src/Pyz/Yves/SalesReturnPage/Theme/default/components/molecules/return-overview/return-overview.twig
  src/Pyz/Yves/SharedCartPage/Theme/default/views/cart-share/cart-share.twig
  src/Pyz/Yves/SharedCartPage/Theme/default/views/dismiss-confirm/dismiss-confirm.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-card/action-card.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/banner/banner.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-icon-list/navigation-icon-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-list/navigation-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
  src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list-dismiss-confirm/shopping-list-dismiss-confirm.twig
Labels: bug, run-ui-ci, run-functional-ci, run-compatibility-ci, run-api-ci, run-latest-ci

#683 CC-36099: fixes security issue with node modules
  package-lock.json
Labels: run-static-ci, run-npm-ci

#678 CC-36077: UI fixes after accessibility improvements
  package-lock.json
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/organisms/filter-section/filter-section.twig
  src/Pyz/Yves/OrderCustomReferenceWidget/Theme/default/components/molecules/order-custom-reference-form/order-custom-reference-form.twig
  src/Pyz/Yves/PaymentPage/Theme/default/templates/page-layout-payment/page-layout-payment.twig
  src/Pyz/Yves/PriceProductVolumeWidget/Theme/default/components/molecules/volume-price/volume-price.scss
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.scss
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/link/link.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/radio/radio.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/title/title.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/pagination/pagination.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/slick-carousel/slick-carousel.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-radio/toggler-radio.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/footer/footer.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.scss
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
Labels: run-ui-ci, run-latest-ci

#684 Removed CustomerReorderWidget.
  composer.json
  composer.lock
  src/Pyz/Yves/CartReorderPage/Theme/default/components/molecules/cart-reorder-form/cart-reorder-form.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder-form/customer-reorder-form.twig
Labels: run-ui-ci

#685 FRW-10742 Fixed duplicated requests during login.
  composer.json
  composer.lock
Labels: bug, run-ui-ci, run-static-ci, run-latest-ci

#686 CC-36086 OA. Yves. Order Total is not updated in the Order History table
  composer.json
  composer.lock
Labels: bug, run-ui-ci, run-latest-ci

#690 FRW-10781 Fixed banner link to the Spryker website
  data/import/common/common/glossary.csv
Labels: bug, run-static-ci

#692 FRW-10788 Updated cypress tests
  composer.lock
Labels: bug, run-ui-ci

#694 FRW-10788 Updated cypress tests
  composer.lock
Labels: bug, run-ui-ci, run-compatibility-ci

#693 CC-36109: button layout on order details page
  data/import/common/common/glossary.csv
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/SalesOrderAmendmentWidget/Theme/default/components/molecules/order-amendment/order-amendment.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-sidebar-item/navigation-sidebar-item.scss
Labels: run-ui-ci
