Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-09, with the labels that each got.

#732 ACP-5354 - Algolia CMS search integration
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.scss
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/sort/index.ts
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/sort/sort.scss
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/sort/sort.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/templates/search-cms-template/search-cms-template.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/views/search/search.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/pagination/pagination.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/pagination/pagination.twig
Labels: run-ui-ci, run-latest-ci

#742 CC-36111: File-based Product Data Import from Merchant Portal UI.
  composer.json
  composer.lock
  config/Shared/config_default-ci.php
  config/Shared/config_default-docker.ci.php
  config/Shared/config_default-docker.dev.php
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  config/Zed/navigation-main-merchant-portal.xml
  data/import/common/common/glossary.csv
  src/Orm/Zed/DataImportMerchant/Persistence/SpyDataImportMerchantFile.php
  src/Orm/Zed/DataImportMerchant/Persistence/SpyDataImportMerchantFileQuery.php
  src/Pyz/Zed/Acl/AclConfig.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/DataImportMerchant/DataImportMerchantConfig.php
  src/Pyz/Zed/DataImportMerchant/DataImportMerchantDependencyProvider.php
  src/Pyz/Zed/DataImportMerchantPortalGui/DataImportMerchantPortalGuiConfig.php
  src/Pyz/Zed/MerchantProductDataImport/MerchantProductDataImportConfig.php
  tsconfig.mp.json
Labels: request-review, run-latest-ci

#759 CC-36431 Hotfix Robot UI tests execution
  .robot/Dockerfile
Labels: run-ui-ci

#753 CI
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  config/install/docker.ci.acceptance-no-mp.yml
  config/install/docker.ci.acceptance.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.robot.yml
  config/install/docker.ci.acceptance.dynamic-store-off.yml
  config/install/docker.ci.acceptance.robot.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.full.yml
  config/install/docker.ci.functional.dynamic-store-off.yml
  deploy.ci.acceptance.dynamic-store-off.robot.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.postgres.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.robot.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.yml
Labels: run-compatibility-ci, run-latest-ci
