Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-03, with the labels that each got.

#549 [All demoshops] Red cypress tests
  .github/workflows/ci.yml
  composer.lock
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  package-lock.json
Labels: run-ui-ci

#553 ACP-4150: Added missing PHPDoc description
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-static-ci

#551 CC-34127 Added CSRF param to Company Role User form.
  composer.lock
  package-lock.json
Labels: run-latest-ci

#560 FRW-9988: Integration
  composer.lock
Labels: run-static-ci

#567 FRW-9983 Integration
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  tests/PyzTest/Yves/Customer/Presentation/CustomerProfileCest.php
  tests/PyzTest/Yves/Customer/_support/PageObject/CustomerProfilePage.php
Labels: run-static-ci, run-latest-ci, run-npm-ci
