Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-06, with the labels that each got.

#633 CC-35461 Order save performance optimization
  composer.lock
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: run-latest-ci

#631 CC-35253: Update Angular to 18
  composer.lock
  package-lock.json
  package.json
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/slick-carousel/slick-carousel.scss
Labels: run-latest-ci

#641 Fixed failed cypress tests.
  composer.lock
  package-lock.json
Labels: run-ui-ci

#634 CC-35706 Backoffice: Add table filters.
  composer.lock
  src/Pyz/Zed/ProductManagement/ProductManagementConfig.php
  src/Pyz/Zed/ProductOfferGui/ProductOfferGuiConfig.php
Labels: run-latest-ci

#639 CC-35839: b2b storefront improvements after accessibility changes
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-summary/cart-summary.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/catalog-cms-block/catalog-cms-block.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/organisms/filter-section/filter-section.scss
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.twig
  src/Pyz/Yves/QuickOrderPage/Theme/default/components/molecules/quick-order-form-actions/quick-order-form-actions.scss
  src/Pyz/Yves/QuickOrderPage/Theme/default/components/molecules/quick-order-form-actions/quick-order-form-actions.twig
  src/Pyz/Yves/QuoteRequestWidget/Theme/default/views/quote-request-create/quote-request-create.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/select/select.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/cart-counter/cart-counter.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/cart-counter/cart-counter.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/user-navigation/user-navigation.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/user-navigation/user-navigation.twig
  src/Pyz/Yves/ShoppingListWidget/Theme/default/views/shopping-list-add-items/shopping-list-add-items.twig
  src/Pyz/Yves/ShoppingListWidget/Theme/default/views/shopping-list-shop-list/shopping-list-shop-list.twig
Labels: run-ui-ci, run-latest-ci

#646 CC-35836: Added queue-based warehouse update functionality.
  composer.json
  composer.lock
  src/Pyz/Zed/Event/EventDependencyProvider.php
  src/Pyz/Zed/Stock/StockConfig.php
Labels: run-latest-ci

#645 Integration: SUPESC-977
  composer.lock
Labels: bug, run-latest-ci
