Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-10, with the labels that each got.

#762 SSP-1196 Attach asset at cart.
  composer.lock
Labels: run-compatibility-ci, run-latest-ci

#761 FRW-9141 Integrated Trufflehog Secret Scanning into CI.
  .github/workflows/ci.yml
Labels: improvement

#766 [CC-36434]: Reconfigure CI to run compatibility checks weekly
  .github/workflows/ci.yml
  .github/workflows/compatibility-ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-compatibility-ci

#771 CC-36466 Bugfixes integration.
  composer.lock
Labels: run-latest-ci

#767 CC-35870 Integration of file-based "Product Offer" Data Import (Merchant Portal)
  composer.json
  composer.lock
  config/Shared/config_default-ci.php
  config/Shared/config_default-docker.ci.php
  config/Shared/config_default-docker.dev.php
  config/Shared/config_default.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/DataImportMerchant/DataImportMerchantConfig.php
  src/Pyz/Zed/DataImportMerchant/DataImportMerchantDependencyProvider.php
  src/Pyz/Zed/DataImportMerchantPortalGui/DataImportMerchantPortalGuiConfig.php
  tsconfig.mp.json
Labels: run-ui-ci, run-compatibility-ci
