Repository spryker-shop/b2b-demo-marketplace, pull requests merged in 2025-08, with the labels that each got.

#701 SUPESC-789 Super attributes don't show values maintained in Backoffice.
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-latest-ci

#703 CC-36115 Integrated bugfixes.
  composer.json
  composer.lock
Labels: run-latest-ci

#717 SUPESC-864 Switching a discount's type doesn't handle the associated voucher codes.
  composer.lock
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: run-latest-ci

#718 CC-35970: Flaky CI. Data Import discount voucher failed
  src/Pyz/Zed/DataImport/Business/Model/DiscountVoucher/DiscountVoucherWriterStep.php
Labels: run-functional-ci

#721 FRW-10805 OTEL Integration.
  .git.docker
  .github/workflows/ci.yml
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/navigation-secondary-merchant-portal.xml
  config/install/docker.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.yml
  package-lock.json
  src/Pyz/Service/Monitoring/MonitoringDependencyProvider.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/AgentSecurityMerchantPortalGui/AgentSecurityMerchantPortalGuiConfig.php
  src/Pyz/Zed/AgentSecurityMerchantPortalGui/AgentSecurityMerchantPortalGuiDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/MultiFactorAuth/MultiFactorAuthDependencyProvider.php
  src/Pyz/Zed/MultiFactorAuthMerchantPortal/MultiFactorAuthMerchantPortalDependencyProvider.php
  src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiConfig.php
  src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiDependencyProvider.php
  src/Pyz/Zed/ZedNavigation/ZedNavigationDependencyProvider.php
  tsconfig.mp.json
Labels: run-ui-ci, run-static-ci, run-functional-ci, run-compatibility-ci, run-api-ci, run-latest-ci, run-npm-ci

#722 Weekly integrations.
  composer.lock
Labels: run-compatibility-ci, run-latest-ci

#727 SUPESC-996 Integration.
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/Log/LogDependencyProvider.php
Labels: bug, run-functional-ci
